создал метки на карте
htmlacademy-javascript/615035-keksobooking-23 pull request #12
Opened 2021-06-30 23:13 UTC by WebOriginals

2021-07-02 21:12 UTC, PolinaShneider commented on js/map.js
> +//import { } from "./random-housing.js";
Закомментированный импорт нужно убрать

2021-07-02 21:17 UTC, PolinaShneider commented on js/map.js
> +// const getStartMarkerAndMap = () => {
А чего ты его закомментировал? Если написать `export const getStartMarkerAndMap`, линтер ругаться не будет

2021-07-02 21:18 UTC, PolinaShneider commented on js/random-housing.js
> +  //similarListFragment.appendChild(adsTemplateElement);
Тоже почему код закомментирован? Если он не нужен, мб, удалить его?

2021-07-02 21:21 UTC, PolinaShneider commented on js/working-form.js
> +  housingCoordinates.value = arrayShortCoordinates.join(', ');
Если я начинаю что-то вводить руками, вот такая ерунда получается
![image](https://user-images.githubusercontent.com/15448200/124329640-6faa3300-db94-11eb-84f9-cea9ef9f97e1.png)

Оно точно так должно работать? Чтобы запретить ручное редактирование поля, достаточно инпуту добавить атрибут `readonly`

2021-07-02 21:23 UTC, PolinaShneider requested changes
Пара минорных замечаний и одна бага

2021-07-03 06:27 UTC, WebOriginals commented on js/working-form.js
> +  housingCoordinates.value = arrayShortCoordinates.join(', ');
я не знал этого атрибута

2021-07-03 08:36 UTC, PolinaShneider commented on js/working-form.js
>    const timeInValue = event.target.value;
![image](https://user-images.githubusercontent.com/15448200/124348478-c8a8b400-dbf2-11eb-9a67-0542152faae6.png)

Эти переменные у тебя избыточные. Можно обойтись без них. Но это уже в следующем реквесте поправишь

2021-07-03 08:36 UTC, PolinaShneider approved these changes
Принято)

2021-07-03 08:36 UTC, merged