создал функцию активации и деактивации форм
htmlacademy-javascript/615035-keksobooking-23 pull request #8
Opened 2021-06-23 15:27 UTC by WebOriginals

2021-06-23 21:57 UTC, PolinaShneider commented on js/workingForm.js
> +const forma = document.querySelector('.ad-form');
Давай переменную назовем просто `form`. Критерии запрещают транслит

2021-06-23 22:03 UTC, PolinaShneider commented on js/workingForm.js
> +const forma = document.querySelector('.ad-form');
И вообще давай-ка добавим суффикс Element. Это критерий [Д6](https://up.htmlacademy.ru/javascript/23/criteries#d6)

2021-06-23 22:04 UTC, PolinaShneider commented on js/workingForm.js
> +activateForm();
Ты специально вызываешь функции? Действие одной перебивает другую, и, не комментируя куски кода, эффект непонятен. Давай лучше функции просто экспортируем — так линтер ругаться не будет. Например, `const activateForm`

2021-06-23 22:06 UTC, PolinaShneider commented on js/workingForm.js
> +const activateForm = function () {
Очень рекомендую пройтись по всем функциям во всех файлах и попытаться привести их к одному виду: https://up.htmlacademy.ru/javascript/23/criteries#d5

2021-06-23 22:07 UTC, PolinaShneider commented on js/workingForm.js
> +    fieldsets[i].removeAttribute('disabled', 'disabled');
removeAttribute принимает только один аргумент (зачем ему значение?)
У тебя WebStorm должен ругаться
![image](https://user-images.githubusercontent.com/15448200/123174319-98417700-d488-11eb-97af-19f5c3425c65.png)

2021-06-23 22:10 UTC, PolinaShneider commented on js/workingForm.js
> +const fieldsets = forma.querySelectorAll('fieldset');
Тут тоже поправь нейминг, плиз

2021-06-23 22:10 UTC, PolinaShneider requested changes
Работает, круто, но пару вещей все же стоит поправить

2021-06-24 09:06 UTC, WebOriginals commented on js/workingForm.js
> +const fieldsets = forma.querySelectorAll('fieldset');
Как мне тут правильно назвать fieldsetsElement ?
С формой понятно formElement.  она единственная . А вот  fieldsets много .

2021-06-24 09:19 UTC, WebOriginals commented on js/workingForm.js
> +activateForm();
Если чсетно не совсем понял что надо . Куда экспортировать "const activateForm".
У меня еще задание такое интересное было  https://up.htmlacademy.ru/javascript/23/tasks/12
сейчас создаем вызов, а в дальнейшем его вызываем . Вот я и вызвал две этих функции  сначала проверил , что  causeDeactivatingForm это корректно работает потом  эта

2021-06-24 09:41 UTC, PolinaShneider commented on js/workingForm.js
> +const fieldsets = forma.querySelectorAll('fieldset');
Я ссылаюсь на критерий) fieldsetsElement звучит странновато, но по критерию правильно

2021-06-24 09:46 UTC, PolinaShneider commented on js/workingForm.js
> +activateForm();
Экспортировать точно по такой же схеме, как ты экспортируешь константы и другие функции. Не обязательно экспортировать куда-то. Ты можешь написать слово export и иметь возможность импортировать при необходимости. Тебе все равно это, скорее всего, придется сделать, когда будешь активацию / деактивацию формы к какому-нибудь функционалу (который будет в другом файле) прикручивать. 

Тот подход, что ты описываешь, хорошо подходит для тренажера, но выглядит странно в рамках проекта. Впрочем, на данном этапе я на этом не настаиваю — ближе к защите убери эти вызовы только

2021-06-24 13:18 UTC, WebOriginals commented on js/workingForm.js
> +activateForm();
я вызов пока дективаяю оставлю , а активация не буду вызывать закину ее как ты говоришь в export

2021-06-24 13:24 UTC, WebOriginals commented on js/workingForm.js
> +const fieldsets = forma.querySelectorAll('fieldset');
Element всегда в конце должен быть ?
adsElementTemplate это ошибка ?

2021-06-24 22:11 UTC, PolinaShneider commented on js/data.js
> +  const getRandomNumberImg = getRandomAvatarIndex === 10 ? getRandomAvatarIndex : `0${getRandomAvatarIndex}`;
Ты проделал большую работу по неймингу функций, молодец. Но здесь мы имеем дело не с функцией, а именно с результатом ее выполнения (в данном случае число)

По правилам нейминг должен быть:
`const something = getSomething()`

то есть что-то (строка, число, объект, массив) получилось в результате вызова функции (у функции уже действие в названии)

2021-06-24 22:12 UTC, PolinaShneider commented on js/data.js
> +  const arrayComfortElements = arrayPhoto;
Зачем тебе это присваивание? Ты можешь просто итерироваться по аргументу без лишней переменной (это вроде тоже какой-то критерий)

2021-06-24 22:14 UTC, PolinaShneider commented on js/data.js
> +  SIMILAR_OBJECTS_COUNT, COMFORT, arrayRussifiedElements, SIMILAR_LIST_FRAGMENT
Что-то я не поняла. Почему у тебя arrayRussifiedElements написан camelCase, но импортируется из файла констант. 

Чуть ниже ты в этот массив пушишь. Мы в константы не пушим) Они на то и константы, чтобы быть неизменяемыми. 

И вообще в файле констант это у тебя пустой массив. Выглядит так, будто место этой переменной в модуле, где ты с ней работаешь

2021-06-24 22:15 UTC, PolinaShneider commented on js/data.js
> +  const arraySrcPhotos = name;
Тоже выглядит как лишнее присваивание) Тебе не надо заводить здесь отдельную переменную для значения из параметра

2021-06-24 22:15 UTC, PolinaShneider commented on js/data.js
> +const createPhotos = (name, tenplate) => {
Опечаточка: надо template

2021-06-24 22:16 UTC, PolinaShneider commented on js/data.js
> +    SIMILAR_LIST_FRAGMENT.appendChild(currentPhotoTemplate);
Почему нейминг как у константы? Это не константа. Во втором реквесте привела примеры констант (и давай все изменения в одном реквесте делать — так меньше путаницы будет)

2021-06-24 22:16 UTC, PolinaShneider commented on js/data.js
> +  photosElement.appendChild(SIMILAR_LIST_FRAGMENT);
У тебя линтер не проходит — поправь, плиз

2021-06-24 22:16 UTC, PolinaShneider commented on js/random-housing.js
> +  COMFORT,
Неиспользуемая переменная, судя по всему

2021-06-24 22:18 UTC, PolinaShneider commented on js/random-housing.js
> +const similarAds = creatingSimilarObjects();
Опять в названии creating. Я понимаю, что не урок английского, но давай напишем create. Это будет звучать как команда "создай" или "создать". Creating  — больше про процесс

2021-06-24 22:18 UTC, PolinaShneider requested changes
Молодец, хорошая работа с критериями, но надо еще чуть-чуть поправить

2021-06-25 07:25 UTC, WebOriginals commented on js/data.js
> +  photosElement.appendChild(SIMILAR_LIST_FRAGMENT);
я так и не смог настроить линтер, я проверяю через сервер когда запушу. и у меня тут нет ошибки . Что надо поправить  " ; - 60ст "?

2021-06-25 20:41 UTC, merged